apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: garbo
resources:
  - ../../base
patches:
  - path: ingress-patch.yaml
  - path: deployment-patch.yaml
images:
  - name: ghcr.io/klimatbyran/pipeline-api
    newTag: "0.1.3" # {"$imagepolicy": "flux-system:pipeline-api:tag"}
